### PR TITLE
Updates the SQL query for extracting tenders & contracts

### PR DESCRIPTION
**Pull request by eltercero**
Related to PopulateTools/issues#1337

### CODE REVIEW

**Review by ferblape — APPROVED** [review]

**Comment by ferblape** [comment]
We might need to coordinate the merge. Once it's merged it's autodeployed. If the ETLs haven't been updated, they'd stop working

**Comment by eltercero** [comment]
> We might need to coordinate the merge. Once it's merged it's autodeployed. If the ETLs haven't been updated, they'd stop working

ok!

I still need to adapt the query, because it's not just the dir3 of the father but all its descendants. I'll ask for another review when it's done.

**Comment by eltercero** [comment]
@blat I updated the query so it fetches tenders/contracts for the public entity with that dir3, but also for its subentities that may have different dir3. Maybe there's an better way to do it?

**Review by ferblape — APPROVED** [review]
I think the query is fine, another way to do it could be with a WITH statement, fetching the parent and the descendants first in an UNION too and using them in the main query, but the result would be the same.

**Comment by ferblape** [comment]
I've verified the sites in staging and they look ok, I'm going to merge this one.

**Pull request merged**
